### ISSUE TITLE
📦 Assignment 1 Deliverables

### ISSUE THREAD

**Issue by jukrb0x** [jukrb0x/swe305-project#24]
## TODOs
- [x] Level 5 Glitch
- [x] Game Over
    - [x] Label
    - [x] Button to back menu 
- [x] Aim after dead (setActive)
- [x] ~~Menu Background~~
- [x] Ending (All levels passed)
- [x] Ammo UI

### Tilemaps
- [x] Fix tilemaps (sorting layers and so on) - In branch `dev`
- [x] Layer issue @1139643975
