### ISSUE TITLE
[Bug Collection] Request for fix on Damage and Collectible, Level Tilemaps

### ISSUE THREAD

**Issue by jukrb0x** [jukrb0x/swe305-project#30]
**TODOs** mentioned in 6ac9ad1 need to be fixed

- [x] character can step over boxes (collider) @KeHu2266
        (both two kinds of boxes)
        ![image](https://user-images.githubusercontent.com/15688641/144744226-6ac43a69-8a77-48a2-8b56-f9be93bfe3af.png)

- [x] Level 6 need map background, ~~and extent of the map (airwall to stop cross over)~~(done) @DenverLeee
        ![image](https://user-images.githubusercontent.com/15688641/144744201-5b41f8db-293b-41d8-86be-b8168835ff18.png)

- [x] @KeHu2266 the border end of the map need to be extended, like the level 6 did (screenshot above), or the airwall and transmission point can be moved forward before screen touching the border of the map.
        ![image](https://user-images.githubusercontent.com/15688641/144744289-6339f145-6586-4a8e-9f32-3ecd2515d709.png)

How's the progress of Collectible? @xiao-fei-xiao00
